language: cpp

os:
  - linux
  - osx

# safelist
branches:
  only:
  - master
  - /v?\d+\.\d+(\.\d+)?/

before_install:
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 6.9.4
  - nvm use 6.9.4
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install -g vsce
  - npm install -g typescript
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent

deploy:
  provider: script
  script: vsce publish -p $VSCE_TOKEN
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_OS_NAME == "linux"
