language: node_js

node_js:
- '6'

os:
- linux
- osx

branches:
  only:
  - master
  - /v?\d+\.\d+(\.\d+)?/

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi

install:
- npm install -g vsce
- npm install -g typescript
- npm install
- npm run vscode:prepublish

script:
- npm test --silent
- vsce package

deploy:
  provider: releases
  api_key:
    secure: YB+wf8pralHqjas4cdP2Ljy6fzs/ysufEhRsSoSU8mV8C/vdzeVm0sxazlRI1JOh9FQl1byVZRrSOoshCOp51EgbCnxMB2RLM+qB4Bq26lOOS8SKXEypRClHJa79kd26QuZtH9A4WoRl/awHz1VWikdawNNK3PPmCJ5G8S3iysRwtUxeCEUA1ZIyhC4mXSBhFKe+fenRfJBctP4Q6HcKxS30xhf5+Bo+8FSH3c1ogOlRD8c70n7DHFcbLW37R+hPsC6XgAFb010teisrVQY8rP+RjzZyRSqL5xjUM8tqJybLAGvFTFSDvI8ql5eyLyTefQHvIIrjpESklNNhj4lCWOlGYw3r8fD7R6/ioPJA4uiAmNJ4ALy8E8K2emHDvxBqaJcPj82HtxKPbZ+Y77n9Twa7Yob38eNoPTEGSoECQvJCLb7BYMC8h6I+suMTm3EcfPn/upgN2zzf+Sb4l3kmsC2LMWoH4OhBquiVxcRXgIo4YRiXOgKKezJUzSMqyltiHfGkodX3s2QYNmEKqrDP6+xwtGDzobyjdJO+Y+3DtKMfYI5AzD8Ll0c6sx+uVcBmSFoWKdZaKfFASUg6JWiItWuwBPtEfXqQv4AS6i64/K9ETJ37OeOl/DnZXWAkAUNG/9MPfCoKjHjMolqs6AcQVr6/KETpqvQLsJRl5gZK5yg=
  file_glob: true
  file: "*.vsix"
  on:
    repo: Microsoft/vscode-arduino
    tags: true
    all_branches: true
    condition: $TRAVIS_OS_NAME == "linux"
