name: Mark stale issues and close them

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: blackchoey/stale@releases/v1.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has no recent activities. It will be closed if no further activity occurs within 3 days. Thank you for your contributions.'
        stale-issue-label: 'stale'
        days-before-stale: 7
        only-labels: 'need more info'
        last-updated-user-type: 'collaborator'
        days-before-close: 3
        operations-per-run: 150
